services:
  - apache
  - mysql
  - php
instances:
  trusty:
    hostname: trusty
    services:
      apache: apache2
      mysql: mysql
      php: php5-fpm
  focal:
    hostname: focal
    services:
      apache: apache2
      mysql: mysql
      php: php7.4-fpm