name: Publish release on GitHub
on:
  push:
    branches: 
      - main
    tags: 
      - v*
jobs:   
  build-release:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Checkout directory
        uses: actions/checkout@v2
      - name: Step 2 - Build Application
        shell: pwsh
        run: |
          mkdir build
          pwsh ./app.ps1 build
      - name: Step 3 - Use the Upload Artifact GitHub Action
        uses: actions/upload-artifact@v2
        with: 
          path: build/wsl-switch-v*.zip
          if-no-files-found: error
  github-release:
    runs-on: ubuntu-latest
    needs: [ build-release ]
    steps:
      - uses: actions/checkout@v2
      - name: Extract version to create Release
        run: echo "::set-output name=version::$( pwsh .\wsl-switch.ps1 version )"
        id: version
      - uses: actions/download-artifact@v2
      - run: cd artifact && sha256sum wsl-switch-v*.zip > sha256sums.txt
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ steps.version.outputs.version }}
          prerelease: false
          draft: false
          body_path: CHANGELOG.md
          files: |
            artifact/*