name: Publish release on GitHub
on:
  push:
    branches: 
      - main
    tags: 
      - v*
jobs:   
  build-release:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Checkout directory
        uses: actions/checkout@v2
      - name: Step 2 - Build Application
        shell: pwsh
        run: pwsh ./app.ps1 build
      - name: Step 3 - Use the Upload Artifact GitHub Action
        uses: actions/upload-artifact@v2
        with: 
          path: ./wsl-switch-v*.zip
          if-no-files-found: error
  github-release:
    runs-on: ubuntu-latest
    needs: [ build-release ]
    steps:
      - uses: actions/download-artifact@v2
      - run: cd artifact && sha256sum wsl-switch-v*.zip > sha256sums.txt
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          body_path: CHANGELOG.md
          files: |
            artifact/*