name: Publish release on GitHub
on:
  push:
    tags: 
      - '**'
jobs:   
  build-release:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Checkout directory
        uses: actions/checkout@v3
      - name: Step 2 - Build Application
        shell: pwsh
        run: |
          mkdir build
          pwsh ./app.ps1 build
      - name: Step 3 - Use the Upload Artifact GitHub Action
        uses: actions/upload-artifact@v3
        with: 
          path: build/wsl-switch-v*.zip
          if-no-files-found: error
  github-release:
    runs-on: ubuntu-latest
    needs: [ build-release ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
      - run: cd artifact && sha256sum wsl-switch-v*.zip > sha256sums.txt
      - uses: softprops/action-gh-release@v1
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          tag_name: ${{ steps.version.outputs.version }}
          prerelease: false
          draft: false
          body_path: CHANGELOG.md
          files: |
            artifact/*
